name:                adventofcode2019
version:             0.1.0.0
github:              "Github username here/adventofcode2019"
license:             BSD3
author:              "Rikard Legge"
maintainer:          "rikard.legge@gmail.com"
copyright:           "2019 Rikard Legge"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RikardLegge/adventofcode2019#readme>

dependencies:
- base >= 4.7 && < 5
- utility-ht == 0.0.14

library:
  source-dirs: src

executables:
  adventofcode2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2019
